### ISSUE TITLE
Submission to Hackage/Stackage?

### ISSUE THREAD

**Issue by nevrome** [lazyppl-team/lazyppl#3]
Really cool library! Did you consider submitting it to Hackage/Stackage to make it a bit more easy to install and use downstream?

**Comment by youqad** [comment]
Hi Clemens! Good idea, we'll do this in the future! 👍

**Comment by nevrome** [comment]
Cool! Having the library on stackage would allow to directly use them in [stack scripts](https://docs.haskellstack.org/en/stable/scripts), which is a pretty convenient format for data analysis.

**Comment by samstaton** [comment]
Thanks for the suggestion. This is now on hackage and stackage (https://hackage.haskell.org/package/lazyppl ).

**Comment by nevrome** [comment]
Fantastic - thanks!
